blank_issues_enabled: false
contact_links:
  - name: Confetti Discord
    url: http://discord.com/invite/jshWA2kRmF
    about: If you are having issues with timings or have other minor issues, come ask us on our Discord server!
  #- name: Dupe / exploits Report
  #  url: http://discord.com/invite/jshWA2kRmF
  #  about: |
  #    Due to GitHub not currently allowing private issues, exploit / dupes reports are currently handled via our Discord.
  #    To report an exploit, see the #paper-exploit-report channel.
